### GET all contacts
GET http://localhost:3000/api/contacts
Accept: application/json

###

### GET contact by ID (reemplaza ID con uno de tus contactos)
GET http://localhost:3000/api/contacts/68d7576f6c2ec498b635a0b9
Accept: application/json

###

### POST create new contact
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "firstName": "Pedro",
  "lastName": "Ramirez",
  "email": "pedro@mail.com",
  "favoriteColor": "orange",
  "birthday": "1993-06-06"
}

###

### PUT update contact (reemplaza ID con uno de tus contactos)
PUT http://localhost:3000/api/contacts/68d7576f6c2ec498b635a0ba
Content-Type: application/json

{
  "firstName": "Pedro",
  "lastName": "Ramirez",
  "email": "pedro_new@mail.com",
  "favoriteColor": "black",
  "birthday": "1993-06-06"
}

###

### DELETE contact (reemplaza ID con uno de tus contactos)
DELETE http://localhost:3000/api/contacts/68d7576f6c2ec498b635a0bb

Accept: application/json
