### GET all contacts
GET http://localhost:3000/api/contacts
Accept: application/json

###

### GET contact by ID - reemplaza con un _id real después de crear
GET http://localhost:3000/api/contacts/{{contactId}}
Accept: application/json

###

### POST create new contact
POST http://localhost:3000/api/contacts
Content-Type: application/json

{
  "firstName": "Sofia",
  "lastName": "Fernandez",
  "email": "sofia@mail.com",
  "favoriteColor": "pink",
  "birthday": "1993-06-06"
}

###

### PUT update contact - reemplaza {{contactId}} con un _id real
PUT http://localhost:3000/api/contacts/{{contactId}}
Content-Type: application/json

{
  "firstName": "Juan",
  "lastName": "Perez",
  "email": "juan_new@mail.com",
  "favoriteColor": "black",
  "birthday": "1990-01-01"
}

###

### DELETE contact - reemplaza {{contactId}} con un _id real
DELETE http://localhost:3000/api/contacts/{{contactId}}
Accept: application/json
